const days=[{label:'Vrijdag',date:'2 oktober',theme:'London, here we come.',events:[['07:00','Verzamelen op Schiphol Plaza','Projectgroep · Nederlandse tijd'],['08:55','Vlucht naar Londen','Vertrek · Nederlandse tijd'],['09:20','Aankomst London Gatwick','Vanaf hier: lokale tijd in Londen'],['10:20','Op weg naar Coca-Cola'],['11:00','Bezoek Coca-Cola','Exacte locatie volgt'],['15:00','Naar het hotel','The Prince Hotel · 49–51 Black Prince Road'],['19:00','Verzamelen in de lobby'],['19:30','Samen aan tafel','Restaurant volgt',true],['21:30','Borrel & de stad in']]},{label:'Zaterdag',date:'3 oktober',theme:'Taste your way through London.',events:[['08:30','Nog in te vullen','Programma volgt',true],['09:00','Ontbijt uit het vuistje'],['10:00','Bread Ahead','Vestiging volgt'],['11:00','Shared lunch'],['12:00','Nog in te vullen','Ruimte in het programma',true],['14:45','Verzamelen bij Embankment Pier','Boot vertrekt 15:00 · vaart tot 15:45'],['16:30','Proeverij','Nog te bevestigen',true],['—','Opfrissen in het hotel','Tijd volgt',true],['—','Verzamelen in de lobby','Tijd volgt',true],['19:30','Samen aan tafel','Restaurant volgt',true],['21:30','Borrel & de stad in']]},{label:'Zondag',date:'4 oktober',theme:'One more bite.',events:[['08:45','Verzamelen in de lobby','Volgorde met ontbijt nog afstemmen',true],['09:00','Ontbijt','Tijd nog afstemmen met vertrek',true],['10:00','Bezoek The Dusty Knuckle','Volgens planning circa 45 minuten met OV vanaf hotel · vestiging volgt'],['11:30','Stadstour'],['13:30','Vertrek naar luchthaven'],['15:00','Aankomst luchthaven','Luchthaven volgt'],['16:55','Vlucht naar huis','Vluchtnummer volgt']]}];
let day=0;const londonDate=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());if(londonDate==='2026-10-03')day=1;if(londonDate==='2026-10-04')day=2;
const view=document.getElementById('view');
function timeline(d){return `<div class="timeline">${d.events.map(e=>`<article class="event"><time>${e[0]}</time><div><h3>${e[1]}</h3>${e[2]?`<p>${e[2]}</p>`:''}${e[3]?'<span class="tag">Onder voorbehoud</span>':''}</div></article>`).join('')}</div>`}
function program(){view.innerHTML=`<div class="section-head"><h2>Jouw weekend.</h2><span class="muted">Tijden zijn lokaal</span></div><div class="days" role="group" aria-label="Kies een dag">${days.map((d,i)=>`<button class="${day===i?'selected':''}" aria-pressed="${day===i}" data-day="${i}"><strong>${d.label}</strong><span>${d.date}</span></button>`).join('')}</div><div class="program-grid"><div>${timeline(days[day])}</div><div class="extras"><section class="feature"><span class="eyebrow">TUSSEN DE BEDRIJVEN DOOR</span><span class="big">£5. Veel smaak.</span><p>Vind de bijzonderste bakkerslekkernij voor maximaal vijf pond.</p><a class="text-link" href="#challenges">Ontdek de challenges ↗</a></section><section class="feature dark"><span class="eyebrow">HANDIG OM TE WETEN</span><h3 style="margin-top:16px">Samen op pad.</h3><p>Hotel, verzamelpunten en reisgegevens op één plek.</p><a class="text-link" href="#praktisch">Praktische info ↗</a></section></div></div>`;view.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{day=+b.dataset.day;program()})}
function challenges(){const cs=[['01','De £5 Challenge','De bijzonderste bakkerslekkernij voor maximaal vijf pond.','Maak een foto van je vondst en noteer de winkel, de prijs en waarom dit jouw winnaar is.'],['02','Steel dit idee','Een vondst die mee terug mag naar jouw bedrijf.','Spot een slim product, een verrassende verpakking of een goede winkelpresentatie. Leg vast wat je aanspreekt en hoe je het zelf zou toepassen.'],['03','Nexus in the wild','Londen als decor. Jullie als hoofdrolspelers.','Maak samen de origineelste groepsfoto van het weekend. Een spontane foto onderweg is net zo welkom als een goed bedacht concept.'],['04','De smaakjury','Welk brood of gebak verdient een Bakery Award?','Noteer jouw favoriet, de bakkerij en je oordeel over smaak, textuur en presentatie.']];view.innerHTML=`<div class="section-head"><h2>Een beetje competitie.</h2><span class="muted">Hele weekend · Vrijblijvend</span></div><p>Doe mee als je zin hebt. Tijdens een bezoek, een vrij moment of onderweg.</p><div class="cards">${cs.map(c=>`<article class="card"><span class="number">${c[0]} ↗</span><h3>${c[1]}</h3><p>${c[2]}</p><details><summary>Bekijk de opdracht</summary><p>${c[3]}</p></details></article>`).join('')}</div><div class="notice">Voorstel voor jullie weekend. Foto’s insturen, gezamenlijk stemmen en de Bakery Awards zijn nog niet actief in deze opzet.</div>`}
const tripPlaces=[
{id:'hotel',name:'The Prince Hotel Vauxhall Central London Riverside',label:'Hotel',when:'Ons verblijf · 2–4 oktober',address:'49–51 Black Prince Road, Londen, SE11 6AB',coords:[51.49133,-0.11824],query:'49-51 Black Prince Road, London SE11 6AB',phone:'+447784603675'},
{id:'pier',name:'Embankment Pier',label:'Boot',when:'Zaterdag · 14:45 aanwezig',address:'Victoria Embankment, Londen',note:'Vertrek 15:00 · terug 15:45',coords:[51.507306,-0.121194],query:'Embankment Pier London'},
{id:'coca-cola',name:'Coca-Cola',when:'Vrijdag · 11:00',note:'Exacte bezoeklocatie volgt.'},
{id:'bread-ahead',name:'Bread Ahead',when:'Zaterdag · 10:00',note:'De geplande vestiging volgt.'},
{id:'dusty-knuckle',name:'The Dusty Knuckle',when:'Zondag · 10:00',note:'De geplande vestiging volgt.'}
];
const routeTo=p=>'https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(p.query);
let placesMap=null;
function places(){view.innerHTML=`<div class="section-head"><h2>Onze stops.</h2><span class="muted">Londen op de kaart</span></div><div id="trip-map" aria-label="Kaart met ons hotel en de bevestigde bezoeklocaties"><p class="map-fallback">Kaart laden… Adressen en routes vind je ook hieronder.</p></div><p id="map-status" class="muted" role="status">Tik op een pin voor de locatie en route. Alleen bekende adressen staan op de kaart.</p><div class="cards">${tripPlaces.map(p=>`<article class="card"><span class="eyebrow">${p.when}</span><h3 style="margin-top:12px">${p.name}</h3><p>${p.address||p.note}${p.address&&p.note?'<br>'+p.note:''}</p>${p.coords?`<div class="place-actions"><a class="route" target="_blank" rel="noopener" href="${routeTo(p)}">Route openen</a><button class="map-focus" data-map-place="${p.id}" hidden>Op de kaart</button>${p.phone?`<a class="text-link" href="tel:${p.phone}">Bel het hotel</a>`:''}</div>`:'<span class="tag">Adres volgt</span>'}</article>`).join('')}</div>`;
if(!window.L){document.querySelector('.map-fallback').textContent='De kaart is niet beschikbaar. Gebruik de routeknoppen hieronder.';return;}
document.getElementById('trip-map').innerHTML='';
placesMap=L.map('trip-map',{scrollWheelZoom:false}).fitBounds(tripPlaces.filter(p=>p.coords).map(p=>p.coords),{padding:[45,45],maxZoom:14});
L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).on('tileerror',()=>{const status=document.getElementById('map-status');if(status)status.textContent='Sommige kaartdelen laden niet. De routeknoppen hieronder blijven beschikbaar.';}).addTo(placesMap);
const markers={};tripPlaces.filter(p=>p.coords).forEach(p=>{markers[p.id]=L.marker(p.coords,{title:p.name,alt:p.name,icon:L.divIcon({className:'trip-pin '+p.id,html:p.id==='hotel'?'H':'B',iconSize:[38,38],iconAnchor:[19,38],popupAnchor:[0,-38]})}).addTo(placesMap).bindPopup(`<strong>${p.name}</strong><p>${p.when}<br>${p.address}</p><a href="${routeTo(p)}" target="_blank" rel="noopener">Route openen</a>`);});
view.querySelectorAll('[data-map-place]').forEach(b=>{b.hidden=false;b.onclick=()=>{const p=tripPlaces.find(p=>p.id===b.dataset.mapPlace);placesMap.setView(p.coords,16);markers[p.id].openPopup();document.getElementById('trip-map').scrollIntoView({behavior:'smooth',block:'center'});};});
}
function practical(){view.innerHTML=`<div class="section-head"><h2>Goed geregeld.</h2></div><div class="cards"><article class="card"><h3>Heenreis · vrijdag 2 oktober</h3><p>07:00 verzamelen op Schiphol Plaza<br>08:55 vertrek vlucht<br>09:20 aankomst London Gatwick</p><span class="tag">Vluchtnummer volgt</span></article><article class="card"><h3>Terugreis · zondag 4 oktober</h3><p>13:30 vertrek naar luchthaven<br>15:00 aankomst luchthaven<br>16:55 vertrek vlucht</p><span class="tag">Luchthaven & vluchtnummer volgen</span></article><article class="card"><h3>Ons hotel</h3><p>The Prince Hotel Vauxhall Central London Riverside<br>49–51 Black Prince Road<br>Londen, SE11 6AB</p><p><a class="route" href="${routeTo(tripPlaces[0])}" target="_blank" rel="noopener">Route naar het hotel</a></p><p><a href="tel:+447784603675">+44 7784 603675</a></p></article><article class="card"><h3>Contact & verzamelen</h3><p>Contactpersoon en telefoonnummer volgen. Verzamelmomenten staan in het dagprogramma.</p></article></div><div class="notice">Alle tijden zijn lokaal: de vertrekactiviteiten op Schiphol in Nederlandse tijd, het programma in Londen in Londense tijd. Zondagochtend moeten ontbijt en verzamelen nog op elkaar worden afgestemd.</div><button class="utility" id="print">Bewaar / print het hele programma ↗</button><p class="muted">Kies in het afdrukvenster ‘Bewaar als PDF’ voor een offline exemplaar.</p>`;document.getElementById('print').onclick=()=>{const previous=view.innerHTML;view.innerHTML=days.map((d,i)=>`<section class="${i?'print-day':''}"><h2>${d.label} ${d.date} · Bakery Nexus</h2><p>Voorlopig programma · tijden lokaal · versie 28 september 2026</p>${timeline(d)}</section>`).join('');window.print();practical()}}
// Deelnemers — centrale lijst. Afbeelding alleen invullen als de illustratie goedgekeurd is.
// Interne briefings staan bewust NIET hier (deze file is openbaar), maar in data/participants-private.json buiten dist.
const people=[
['david-van-maanen','David','Van Maanen',true],
['nick-eversdijk','Nick','Eversdijk',true,'assets/people/nick-eversdijk','https://bakerynexus.nl/wp-content/uploads/2023/12/Nick.jpeg','Cartoon van Nick die in Londen twee telefoongesprekken tegelijk voert: een smartphone aan zijn oor en de hoorn van een rode telefooncel in zijn andere hand, met Big Ben op de achtergrond.'],
['lieke-schoenmakers','Lieke','Schoenmakers',true,'assets/people/lieke-schoenmakers','https://bakerynexus.nl/wp-content/uploads/2026/05/Lieke-Schoenmakers.png','Cartoon van Lieke in trenchcoat en luipaardblouse, met een Engelse kop thee en een croissant, voor Big Ben en een rode telefooncel.'],
['mitchel-ammerlaan','Mitchel','Ammerlaan',true],
['jarno-ammerlaan','Jarno','Ammerlaan'],
['bas-post','Bas','Post'],
['jeroen-heemskerk','Jeroen','Heemskerk'],
['richard-huisman','Richard','Huisman'],
['robin-kruikenmeier','Robin','Kruikenmeier'],
['jeroen-hutten','Jeroen','Hutten'],
['maria-luis-brandao','Maria Luis','Brandáo'],
['india-soeteman','India','Soeteman'],
['kelly-van-de-kletersteeg','Kelly','van de Kletersteeg'],
['maurits-casteleijn','Maurits','Casteleijn'],
['wout-nollen','Wout','Nollen'],
['anke-daling','Anke','Daling'],
['emilie-tolhuisen','Emilie','Tolhuisen'],
['rico-romijn','Rico','Romijn'],
['jim-van-aken','Jim','van Aken'],
['anne-van-kraaij','Anne','van Kraaij']
].map(([id,voornaam,achternaam,projectgroep=false,afbeelding=null,bronfoto=null,alt=''])=>({id,voornaam,achternaam,projectgroep,afbeelding,bronfoto,alt}));
const fullName=p=>`${p.voornaam} ${p.achternaam}`;
const initials=p=>(p.voornaam[0]+p.achternaam.split(' ').filter(w=>!/^(van|de|der|den)$/.test(w)).pop()[0]).toUpperCase();
function personCard(p){const tag=p.projectgroep?'<span class="pg">Projectgroep</span>':'';
if(p.afbeelding)return `<li><button class="person" data-person="${p.id}" aria-haspopup="dialog"><img src="${p.afbeelding}-480.webp" width="480" height="480" loading="lazy" decoding="async" alt="${p.alt}"><span class="pname">${fullName(p)}</span>${tag}<span class="sr">, bekijk grote illustratie</span></button></li>`;
return `<li><div class="person pending"><span class="initials" aria-hidden="true">${initials(p)}</span><span class="pname">${fullName(p)}</span>${tag}<span class="soon">Cartoon volgt</span></div></li>`}
function group(){const done=people.filter(p=>p.afbeelding).length;view.innerHTML=`<div class="section-head"><h2>De groep.</h2><span class="muted">${people.length} deelnemers · ${done} cartoons klaar</span></div><p class="group-intro">Iedereen krijgt een eigen Londens personage. Tik op een cartoon om hem groot te bekijken.</p><ul class="people">${people.map(personCard).join('')}</ul><dialog id="person-dialog" aria-labelledby="pd-title"><form method="dialog"><button class="pd-close" aria-label="Sluiten">✕</button></form><img id="pd-img" width="1080" height="1080" alt=""><p id="pd-title"></p></dialog>`;
const dlg=document.getElementById('person-dialog');view.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>{const p=people.find(x=>x.id===b.dataset.person);const img=document.getElementById('pd-img');img.src=p.afbeelding+'.webp';img.alt=p.alt;document.getElementById('pd-title').textContent=fullName(p);dlg.showModal()});
dlg.addEventListener('click',e=>{if(e.target===dlg)dlg.close()})}
function render(){if(placesMap){placesMap.remove();placesMap=null;}const route=location.hash.slice(1)||'programma';document.querySelectorAll('nav a').forEach(a=>{const active=a.hash==='#'+route;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});({programma:program,groep:group,challenges,plekken:places,praktisch:practical}[route]||program)()}
window.addEventListener('hashchange',()=>{render();view.scrollIntoView({behavior:'smooth',block:'start'})});render();
