const days=[{label:'Vrijdag',date:'2 oktober',theme:'London, here we come.',events:[['07:00','Verzamelen op Schiphol Plaza','Iedereen · Nederlandse tijd'],['07:55','Bagageafgifte sluit','Balie open vanaf 06:25 · Nederlandse tijd'],['08:55','Vlucht naar Londen · easyJet EZY8673','Amsterdam Schiphol → London Gatwick · Nederlandse vertrektijd'],['09:20','Aankomst London Gatwick · North Terminal','Vanaf hier: lokale tijd in Londen'],['10:20','Op weg naar Coca-Cola'],['11:00','Bezoek Coca-Cola','Cray Road, Sidcup DA14 5DF'],['15:00','Naar het hotel','The Prince Hotel · 49–51 Black Prince Road'],['19:00','Verzamelen in de lobby'],['19:30','Diner bij Market Place Food Hall Vauxhall','7–11 South Lambeth Road, SW8 1SP'],['21:30','Borrel & de stad in']]},{label:'Zaterdag',date:'3 oktober',theme:'Taste your way through London.',events:[['08:45','Vertrek vanaf het hotel'],['09:00','Ontbijt uit het vuistje'],['10:00','Bread Ahead','Borough Market · Cathedral Street, SE1 9DE'],['11:00','Shared lunch'],['12:00','Foodmarkt-tour','Proeven en rondkijken op verschillende Londense foodmarkten'],['14:45','Verzamelen bij Embankment Pier','Boot vertrekt 15:00 · vaart tot 15:45'],['15:45','Vrije tijd','Na de boottocht'],['—','Opfrissen in het hotel','Tijd volgt',true],['—','Verzamelen in de lobby','Tijd volgt',true],['19:30','Diner bij Pizza Pilgrims Victoria','32–34 Buckingham Palace Road, SW1W 0QP'],['21:30','Borrel & de stad in']]},{label:'Zondag',date:'4 oktober',theme:'One more bite.',events:[['08:45','Verzamelen in de lobby'],['10:00','Ontbijt bij The Dusty Knuckle','Tot 11:30 · Dalston · Abbot Street Car Park, E8 3DP'],['11:30','Richting het centrum · vrije tijd','Tot vertrek naar Gatwick'],['—','Met het openbaar vervoer naar London Gatwick','Vanuit het centrum · vertrektijd volgt',true],['—','Aankomst London Gatwick','Tijd en vertrekterminal volgen',true],['15:20','Vlucht naar huis · easyJet EZY8688','London Gatwick → Amsterdam Schiphol · Londense vertrektijd'],['17:40','Aankomst Amsterdam Schiphol','Nederlandse tijd']]}];
let day=0;const londonDate=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/London',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());if(londonDate==='2026-10-03')day=1;if(londonDate==='2026-10-04')day=2;
const view=document.getElementById('view');
function timeline(d){return `<div class="timeline">${d.events.map(e=>`<article class="event"><time>${e[0]}</time><div><h3>${e[1]}</h3>${e[2]?`<p>${e[2]}</p>`:''}${e[3]?'<span class="tag">Onder voorbehoud</span>':''}</div></article>`).join('')}</div>`}
function program(){view.innerHTML=`<div class="section-head"><h2>Jouw weekend.</h2><span class="muted">Tijden zijn lokaal</span></div><div class="days" role="group" aria-label="Kies een dag">${days.map((d,i)=>`<button class="${day===i?'selected':''}" aria-pressed="${day===i}" data-day="${i}"><strong>${d.label}</strong><span>${d.date}</span></button>`).join('')}</div><div class="program-grid"><div>${timeline(days[day])}</div><div class="extras"><section class="feature"><span class="eyebrow">TUSSEN DE BEDRIJVEN DOOR</span><span class="big">Last Orders.</span><p>Wie maakt de beste kroegfoto? Of zingt het mooist bij de karaoke?</p><a class="text-link" href="#challenges">Bekijk de challenges ↗︎</a></section><section class="feature dark"><span class="eyebrow">HANDIG OM TE WETEN</span><h3 style="margin-top:16px">Samen op pad.</h3><p>Hotel, verzamelpunten en reisgegevens op één plek.</p><a class="text-link" href="#praktisch">Praktische info ↗︎</a></section></div></div>`;view.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{day=+b.dataset.day;program()})}

const tripPlaces=[
{id:'hotel',name:'The Prince Hotel Vauxhall Central London Riverside',label:'Hotel',when:'Ons verblijf · 2–4 oktober',address:'49–51 Black Prince Road, Londen, SE11 6AB',coords:[51.49133,-0.11824],query:'49-51 Black Prince Road, London SE11 6AB',phone:'+447784603675'},
{id:'pier',name:'Embankment Pier',label:'Boot',when:'Zaterdag · 14:45 aanwezig',address:'Victoria Embankment, Londen',note:'Vertrek 15:00 · vaart tot 15:45',coords:[51.507306,-0.121194],query:'Embankment Pier London'},
{id:'coca-cola',buitenKaart:true,name:'Coca-Cola',label:'CC',when:'Vrijdag · 11:00',address:'Cray Road, Sidcup DA14 5DF',coords:[51.4160742,0.1175609],query:'Cray Rd, Sidcup DA14 5DF, United Kingdom'},
{id:'bread-ahead',name:'Bread Ahead · Borough Market',label:'BA',when:'Zaterdag · 10:00',address:'Borough Market, Cathedral Street, Londen SE1 9DE',coords:[51.5060102,-0.090434],query:'Bread Ahead Borough Market Cathedral Street London',source:'https://www.breadahead.com/borough'},
{id:'dusty-knuckle',buitenKaart:true,name:'The Dusty Knuckle · Dalston',label:'DK',when:'Zondag · ontbijt 10:00–11:30',address:'Abbot Street Car Park, Londen E8 3DP',coords:[51.5471,-0.07415],query:'The Dusty Knuckle Abbot Street London E8 3DP',source:'https://www.thedustyknuckle.com/dalston-cafe'},
{id:'market-place',name:'Market Place Food Hall Vauxhall',label:'MP',when:'Vrijdag · diner · 19:30',address:'7–11 South Lambeth Road, Londen SW8 1SP',coords:[51.48557,-0.12287],query:'Market Place Food Hall Vauxhall 7-11 South Lambeth Road London SW8 1SP',source:'https://www.marketplacefoodhall.com/locations/vauxhall'},
{id:'pizza-pilgrims',name:'Pizza Pilgrims Victoria',label:'PP',when:'Zaterdag · diner · 19:30',address:'32–34 Buckingham Palace Road, Londen SW1W 0QP',coords:[51.4973062,-0.1446368],query:'Pizza Pilgrims 32-34 Buckingham Palace Road London SW1W 0QP'}
];
const routeTo=p=>'https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(p.query);
let placesMap=null;
function places(){view.innerHTML=`<div class="section-head"><h2>Onze stops.</h2><span class="muted">Londen op de kaart</span></div><div id="trip-map" aria-label="Kaart met ons hotel, bezoeken en dinerlocaties"><p class="map-fallback">Kaart laden… Adressen en routes vind je ook hieronder.</p></div><p id="map-status" class="muted" role="status">Tik op een pin voor de locatie en route.</p><div class="cards">${tripPlaces.map(p=>`<article class="card"><span class="eyebrow">${p.when}</span><h3 style="margin-top:12px">${p.name}</h3><p>${p.address||p.note}${p.address&&p.note?'<br>'+p.note:''}</p>${p.provisional?'<span class="tag">Vestiging te bevestigen</span>':''}${p.source?`<p><a class="text-link" href="${p.source}" target="_blank" rel="noopener">Website locatie</a></p>`:''}${p.coords?`<div class="place-actions"><a class="route" target="_blank" rel="noopener" href="${routeTo(p)}">Route openen</a>${p.buitenKaart?'':`<button class="map-focus" data-map-place="${p.id}" hidden>Op de kaart</button>`}${p.phone?`<a class="text-link" href="tel:${p.phone}">Bel het hotel</a>`:''}</div>`:'<span class="tag">Adres volgt</span>'}</article>`).join('')}</div>`;
if(!window.L){document.querySelector('.map-fallback').textContent='De kaart is niet beschikbaar. Gebruik de routeknoppen hieronder.';return;}
document.getElementById('trip-map').innerHTML='';
placesMap=L.map('trip-map',{scrollWheelZoom:false}).fitBounds(tripPlaces.filter(p=>p.coords&&!p.buitenKaart).map(p=>p.coords),{padding:[45,45],maxZoom:14});
L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).on('tileerror',()=>{const status=document.getElementById('map-status');if(status)status.textContent='Sommige kaartdelen laden niet. De routeknoppen hieronder blijven beschikbaar.';}).addTo(placesMap);
const markers={};tripPlaces.filter(p=>p.coords&&!p.buitenKaart).forEach(p=>{markers[p.id]=L.marker(p.coords,{title:p.name,alt:p.name,icon:L.divIcon({className:'trip-pin '+p.id+(p.provisional?' provisional':''),html:p.id==='hotel'?'H':p.id==='pier'?'B':p.label,iconSize:[38,38],iconAnchor:[19,38],popupAnchor:[0,-38]})}).addTo(placesMap).bindPopup(`<strong>${p.name}</strong><p>${p.when}<br>${p.address}${p.note?'<br>'+p.note:''}</p><a href="${routeTo(p)}" target="_blank" rel="noopener">Route openen</a>`);});
view.querySelectorAll('[data-map-place]').forEach(b=>{b.hidden=false;b.onclick=()=>{const p=tripPlaces.find(p=>p.id===b.dataset.mapPlace);placesMap.setView(p.coords,16);markers[p.id].openPopup();document.getElementById('trip-map').scrollIntoView({behavior:'smooth',block:'center'});};});
}
const kamers=[['David','Mitchel'],['Rico','Jim'],['Jeroen Hutten','Wout'],['Bas','Robin'],['Richard','Jarno'],['Maurits','Jeroen Heemskerk'],['Nick','Kelly'],['Anne','Maria'],['Emelie','India'],['Lieke','Anke']];
function practical(){view.innerHTML=`<div class="section-head"><h2>Goed geregeld.</h2></div><div class="cards"><article class="card"><h3>Heenreis · vrijdag 2 oktober</h3><p><strong>easyJet · EZY8673</strong><br>Amsterdam Schiphol → London Gatwick<br>07:00 verzamelen op Schiphol Plaza<br>08:55 vertrek (Nederlandse tijd)<br>09:20 aankomst (Londense tijd)<br>Aankomstterminal: North Terminal</p><p><strong>Bagageafgifte</strong><br>Open: 06:25 · sluit: 07:55<br>De incheckbalie sluit 60 minuten voor vertrek.</p><p class="muted">Controleer voor vertrek de actuele vluchtinformatie bij easyJet.</p></article><article class="card"><h3>Terugreis · zondag 4 oktober</h3><p><strong>easyJet · EZY8688 (U2 8688)</strong><br>London Gatwick (LGW) → Amsterdam Schiphol (AMS)<br>15:20 vertrek (Londense tijd)<br>17:40 aankomst (Nederlandse tijd)</p><p>Vertrekterminal en bagageafgiftetijden volgen.</p><p>We reizen met het openbaar vervoer vanuit het centrum naar Gatwick. Vertrektijd volgt.</p></article><article class="card"><h3>Ons hotel</h3><p>The Prince Hotel Vauxhall Central London Riverside<br>49–51 Black Prince Road<br>Londen, SE11 6AB</p><p><a class="route" href="${routeTo(tripPlaces[0])}" target="_blank" rel="noopener">Route naar het hotel</a></p><p><a href="tel:+447784603675">+44 7784 603675</a></p></article><article class="card"><h3>Kamerindeling</h3><ul class="rooms">${kamers.map(k=>`<li>${k.join(' <span>&amp;</span> ')}</li>`).join('')}</ul></article></div><div class="notice">Alle tijden zijn lokaal: de vertrekactiviteiten op Schiphol in Nederlandse tijd, het programma in Londen in Londense tijd en de aankomst op Schiphol in Nederlandse tijd.</div><button class="utility" id="print">Bewaar / print het hele programma ↗︎</button><p class="muted">Kies in het afdrukvenster ‘Bewaar als PDF’ voor een offline exemplaar.</p>`;document.getElementById('print').onclick=()=>{const previous=view.innerHTML;view.innerHTML=days.map((d,i)=>`<section class="${i?'print-day':''}"><h2>${d.label} ${d.date} · Bakery Nexus</h2><p>Programma · tijden lokaal · bijgewerkt 30 september 2026</p>${timeline(d)}</section>`).join('');window.print();practical()}}
// Deelnemers — centrale lijst. Afbeelding alleen invullen als de illustratie goedgekeurd is.
// Interne briefings staan bewust NIET hier (deze file is openbaar), maar in data/participants-private.json buiten dist.
const people=[
['david-van-maanen','David','Van Maanen',true,'assets/people/david-van-maanen',null,'Cartoon van David die bij Borough Market een vlog opneemt met zijn telefoon en trots een ingesneden zuurdesembrood laat zien.'],
['nick-eversdijk','Nick','Eversdijk',true,'assets/people/nick-eversdijk','https://bakerynexus.nl/wp-content/uploads/2023/12/Nick.jpeg','Cartoon van Nick die in Londen twee telefoongesprekken tegelijk voert: een smartphone aan zijn oor en de hoorn van een rode telefooncel in zijn andere hand, met Big Ben op de achtergrond.'],
['lieke-schoenmakers','Lieke','Schoenmakers',true,'assets/people/lieke-schoenmakers','https://bakerynexus.nl/wp-content/uploads/2026/05/Lieke-Schoenmakers.png','Cartoon van Lieke in trenchcoat en luipaardblouse, met een Engelse kop thee en een croissant, voor Big Ben en een rode telefooncel.'],
['mitchel-ammerlaan','Mitchel','Ammerlaan',true,'assets/people/mitchel-ammerlaan',null,'Cartoon van Mitchel die als een dirigent een Londense bakkerij leidt, met een productielijst in de ene hand en een stokbrood als dirigeerstok in de andere.'],
['jarno-ammerlaan','Jarno','Ammerlaan',false,'assets/people/jarno-ammerlaan',null,'Cartoon van Jarno die room spuit op een piepkleine Tower Bridge-taart, met een Londense etalage en rode telefooncel op de achtergrond.'],
['bas-post','Bas','Post',false,'assets/people/bas-post',null,'Cartoon van Bas die als grondstoffenverkoper een schepje meel aanprijst als een Londense schat, naast een zadenbrood en een monsterkoffer.'],
['jeroen-heemskerk','Jeroen','Heemskerk',false,'assets/people/jeroen-heemskerk',null,'Cartoon van Jeroen Heemskerk die op een Londens terras met een reuzenrekenmachine de kostprijs van een croissant uitrekent.'],
['richard-huisman','Richard','Huisman',false,'assets/people/richard-huisman',null,'Cartoon van Richard die met een enorme spuitzak petitfours afwerkt, waarvan er één op een rode Londense bus lijkt.'],
['robin-kruikenmeier','Robin','Kruikenmeier',false,'assets/people/robin-kruikenmeier',null,'Cartoon van Robin met zonnebril die een reusachtig taartpunt presenteert aan een Londense high-tea-toonbank.'],
['jeroen-hutten','Jeroen','Hutten',false,'assets/people/jeroen-hutten',null,'Cartoon van Jeroen Hutten die een nieuw spiraalgebakje met een vergrootglas bestudeert als een uitvinding.'],
['maria-luis-brandao','Maria Luis','Brandáo',false,'assets/people/maria-luis-brandao',null,'Cartoon van Maria die in een Londens café een croissant fotografeert en een lampje bijstelt, met een rode bus op de achtergrond.'],
['india-soeteman','India','Soeteman',false,'assets/people/india-soeteman',null,'Cartoon van India met een overborrelende pot zuurdesemstarter en een deegschraper, naast een mooi ingesneden brood bij Borough Market.'],
['kelly-van-de-kletersteeg','Kelly','van de Kletersteeg',false,'assets/people/kelly-van-de-kletersteeg',null,'Cartoon van Kelly die trots een grote spiraalkneder demonstreert in een Londense bakkerij.'],
['maurits-casteleijn','Maurits','Casteleijn',false,'assets/people/maurits-casteleijn',null,'Cartoon van Maurits die een monsterkoffer vol minibroodjes en potjes grondstoffen opent alsof het juwelen zijn.'],
['wout-nollen','Wout','Nollen',false,'assets/people/wout-nollen',null,'Cartoon van Wout die een vol blik verse broden balanceert en ondertussen een productielijst afvinkt.'],
['anke-daling','Anke','Daling',false,'assets/people/anke-daling',null,'Cartoon van Anke die in een Londens café lachend wijst naar een stijgende grafiek van croissants op haar laptop.'],
['emilie-tolhuisen','Emelie','Tolhuisen',false,'assets/people/emilie-tolhuisen',null,'Cartoon van Emelie met lang rood haar die een Londense taart met Big Ben, de London Eye en garde-soldaatjes afwerkt met een spuitzak.'],
['rico-romijn','Rico','Romijn',false,'assets/people/rico-romijn',null,'Cartoon van Rico die als testbakker een flinterdun vliesje deeg uitrekt, met proefbroodjes en een weegschaal op de werkbank.'],
['jim-van-aken','Jim','van Aken',false,'assets/people/jim-van-aken',null,'Cartoon van Jim die onder een zilveren stolp een overdadig luxe brood onthult.'],
['anne-van-kraaij','Anne','van Kraaij',false,'assets/people/anne-van-kraaij',null,'Cartoon van Anne die met een liniaaltje een croissant precies op zijn plek legt in een winkelpresentatie.']
].map(([id,voornaam,achternaam,projectgroep=false,afbeelding=null,bronfoto=null,alt=''])=>({id,voornaam,achternaam,projectgroep,afbeelding,bronfoto,alt}));
const fullName=p=>`${p.voornaam} ${p.achternaam}`;
const initials=p=>(p.voornaam[0]+p.achternaam.split(' ').filter(w=>!/^(van|de|der|den)$/.test(w)).pop()[0]).toUpperCase();
function personCard(p){const tag=p.projectgroep?'<span class="pg">Projectgroep</span>':'';
if(p.afbeelding)return `<li><button class="person" data-person="${p.id}" aria-haspopup="dialog"><img src="${p.afbeelding}-480.webp" width="480" height="480" loading="lazy" decoding="async" alt="${p.alt}"><span class="pname">${fullName(p)}</span>${tag}<span class="sr">, bekijk grote illustratie</span></button></li>`;
return `<li><div class="person pending"><span class="initials" aria-hidden="true">${initials(p)}</span><span class="pname">${fullName(p)}</span>${tag}<span class="soon">Cartoon volgt</span></div></li>`}
function group(){const done=people.filter(p=>p.afbeelding).length;view.innerHTML=`<figure class="group-hero"><div class="hero-scroll"><button class="hero-btn" id="hero-open" aria-label="Groepscartoon groot bekijken"><img src="assets/group/groep.webp" srcset="assets/group/groep-1000.webp 1000w, assets/group/groep.webp 1448w" sizes="(max-width:700px) 100vw, 1100px" width="1448" height="1086" alt="Groepscartoon van de Bakery Nexus-groep voor Tower Bridge, alle twintig met hun eigen bakkersvak"></button></div></figure><div class="section-head"><h2>De groep.</h2><span class="muted">${people.length} deelnemers · ${done} cartoons klaar</span></div><p class="group-intro">Iedereen heeft een eigen Londens personage. Tik op een cartoon om hem groot te bekijken.</p><ul class="people">${people.map(personCard).join('')}</ul><dialog id="person-dialog" aria-labelledby="pd-title"><form method="dialog"><button class="pd-close" aria-label="Sluiten">✕</button></form><img id="pd-img" width="1080" height="1080" alt=""><p id="pd-title"></p></dialog>`;
const dlg=document.getElementById('person-dialog');document.getElementById('hero-open').onclick=()=>{const img=document.getElementById('pd-img');img.src='assets/group/groep.webp';img.alt='Groepscartoon van de Bakery Nexus-groep voor Tower Bridge';document.getElementById('pd-title').textContent='Bakery Nexus × London';dlg.classList.add('breed');dlg.showModal()};dlg.addEventListener('close',()=>dlg.classList.remove('breed'));view.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>{const p=people.find(x=>x.id===b.dataset.person);const img=document.getElementById('pd-img');img.src=p.afbeelding+'.webp';img.alt=p.alt;document.getElementById('pd-title').textContent=fullName(p);dlg.showModal()});
dlg.addEventListener('click',e=>{if(e.target===dlg)dlg.close()})}
// Inspiratieboek: foto's en notities centraal in Supabase.
// Persoonlijke link (#ik=…) = kijken en toevoegen onder eigen naam; groepscode = alleen kijken.
const IDEE_API='https://rpbiwpjkaysxyhfrbljl.supabase.co/functions/v1/hyper-function',IDEE_KEY='sb_publishable_9IxzTaZfDP2fIS3Rgptxuw_9B_6tu2T';
const categorieen=['Product','Smaakinspiratie','Verpakking','Interieur','Concept','Overig'];
const opslag={lees(k){try{return localStorage.getItem(k)||''}catch(e){return''}},zet(k,v){try{v?localStorage.setItem(k,v):localStorage.removeItem(k)}catch(e){}}};
const linkSleutel=(location.hash.match(/^#ik=([\w-]{10,100})$/)||[])[1];if(linkSleutel&&linkSleutel!==opslag.lees('nexusSleutel')){opslag.zet('nexusSleutel',linkSleutel);opslag.zet('nexusNaam','')}
let ideeen=null,ideeFilter='Alle',ideeBeheer=false;
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function ideeApi(body){const form=body instanceof FormData,headers={apikey:IDEE_KEY,'x-groepscode':opslag.lees('nexusGroepscode')},sl=opslag.lees('nexusSleutel');if(sl)headers['x-deelnemer']=sl;const b=opslag.lees('nexusBeheercode');if(b)headers['x-beheercode']=b;if(!form)headers['content-type']='application/json';
let r;try{r=await fetch(IDEE_API,{method:'POST',headers,body:form?body:JSON.stringify(body)})}catch(e){throw new Error('Geen verbinding met de server')}
const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.fout||`Serverfout (${r.status})`);e.status=r.status;throw e}return d}
function verklein(file,max,q){return new Promise((ok,nok)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const s=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight)),c=document.createElement('canvas');c.width=Math.round(img.naturalWidth*s);c.height=Math.round(img.naturalHeight*s);c.getContext('2d').drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);c.toBlob(b=>b?ok(b):nok(new Error('De foto kon niet worden verkleind')),'image/jpeg',q)};img.onerror=()=>{URL.revokeObjectURL(url);nok(new Error('Dit fotobestand kan niet worden gelezen'))};img.src=url})}
const ideeKop=`<div class="section-head"><h2>Inspiratieboek.</h2><span class="muted">Alleen voor de groep</span></div>`;
function ideeUit(melding){['nexusSleutel','nexusNaam','nexusGroepscode'].forEach(k=>opslag.zet(k,''));ideeen=null;inspiration(melding)}
function inspiration(melding){const code=opslag.lees('nexusGroepscode'),sleutel=opslag.lees('nexusSleutel'),naam=opslag.lees('nexusNaam');
if(sleutel&&!naam){view.innerHTML=`${ideeKop}<p class="muted">Even kijken wie je bent…</p>`;ideeApi({actie:'controle'}).then(d=>{if(!d.naam)return ideeUit('Deze persoonlijke link is niet (meer) geldig. Vraag de organisatie om een nieuwe.');opslag.zet('nexusNaam',d.naam);inspiration()}).catch(err=>err.status===401?ideeUit(err.message):view.innerHTML=`${ideeKop}<p class="notice">${esc(err.message)}. Probeer het later opnieuw.</p>`);return}
if(!sleutel&&!code){view.innerHTML=`${ideeKop}${melding?`<p class="notice">${esc(melding)}</p>`:''}<p class="group-intro">Proef je iets moois of zie je een slim idee? Leg het vast met een foto, zodat de hele groep het terugziet.</p><div class="card"><h3>Je persoonlijke link</h3><p>Open de link die je in de groepsapp kreeg. Dan herkent de site je meteen en kun je ideeën toevoegen.</p></div><form class="card idea-form" id="code-form" style="margin-top:18px"><label>Alleen meekijken? Vul de groepscode in<input name="code" autocomplete="off" autocapitalize="off" required></label><button class="utility">Bekijk het inspiratieboek</button><p class="muted" id="code-status" role="status"></p></form>`;
const f=document.getElementById('code-form');f.onsubmit=async e=>{e.preventDefault();const st=document.getElementById('code-status');st.textContent='Controleren…';opslag.zet('nexusGroepscode',f.code.value.trim());try{await ideeApi({actie:'controle'});inspiration()}catch(err){opslag.zet('nexusGroepscode','');st.textContent=err.message}};return}
const tip=sleutel&&!opslag.lees('nexusTipWeg')?`<div class="notice" id="idee-tip"><strong>Welkom ${esc(naam.split(' ')[0])}!</strong> Zet de site nu op je beginscherm, dan blijf je herkend. iPhone: <em>Deel</em> → <em>Zet op beginscherm</em>. Android: <em>⋮</em> → <em>Toevoegen aan startscherm</em>. <button class="linkish" id="idee-tip-weg">Begrepen</button></div>`:'';
const toevoegen=sleutel?`<details class="card idea-add"${ideeen&&!ideeen.length?' open':''}><summary>+ Idee vastleggen</summary><form class="idea-form" id="idee-form"><label>Foto<input type="file" name="foto" accept="image/*" required></label><img id="idee-preview" alt="" hidden><label>Titel<input name="titel" maxlength="120" required placeholder="Bijv. croissant met miso-karamel"></label><label>Categorie<select name="categorie" required><option value="">Kies een categorie</option>${categorieen.map(c=>`<option>${c}</option>`).join('')}</select></label><label>Notitie<textarea name="notitie" maxlength="2000" rows="4" placeholder="Wat maakt dit bijzonder? Hoe passen we het zelf toe?"></textarea></label><label>Locatie <span class="muted">(optioneel)</span><select name="locatie"><option value="">Geen</option>${tripPlaces.map(p=>`<option>${esc(p.name)}</option>`).join('')}<option>Onderweg</option></select></label><button class="utility" id="idee-opslaan">Opslaan</button><p id="idee-status" class="muted" role="status"></p></form></details>`:'<p class="notice">Je kijkt mee met de groepscode. Zelf iets toevoegen? Open je persoonlijke link uit de groepsapp.</p>';
view.innerHTML=`${ideeKop}${tip}${toevoegen}<div id="idee-bord"></div><div class="chips" id="idee-filter" role="group" aria-label="Filter op categorie"></div><div id="idee-galerij"><p class="muted">Ideeën laden…</p></div><p class="muted idea-me">${sleutel?`Je voegt toe als <strong>${esc(naam)}</strong>`:'Alleen meekijken'} · <button class="linkish" id="idee-beheer">${ideeBeheer?'beheer actief':'beheer'}</button></p><dialog id="idee-dialog" aria-labelledby="id-title"><form method="dialog"><button class="pd-close" aria-label="Sluiten">✕</button></form><img id="id-img" alt=""><div class="id-body"><p class="eyebrow" id="id-meta"></p><h3 id="id-title"></h3><p class="id-door" id="id-door"></p><p id="id-note"></p><div id="id-score"></div><button class="map-focus" id="id-del" hidden>Verwijderen</button></div></dialog>`;
const tw=document.getElementById('idee-tip-weg');if(tw)tw.onclick=()=>{opslag.zet('nexusTipWeg','1');document.getElementById('idee-tip').remove()};
const f=document.getElementById('idee-form'),st=document.getElementById('idee-status'),pv=document.getElementById('idee-preview');if(f){
f.foto.onchange=()=>{const file=f.foto.files[0];if(pv.src)URL.revokeObjectURL(pv.src);if(file){pv.src=URL.createObjectURL(file);pv.hidden=false}else{pv.removeAttribute('src');pv.hidden=true}};
f.onsubmit=async e=>{e.preventDefault();const btn=document.getElementById('idee-opslaan'),file=f.foto.files[0];if(!file)return;btn.disabled=true;st.textContent='Foto verkleinen…';
try{const[groot,klein]=await Promise.all([verklein(file,1600,.82),verklein(file,480,.75)]);const fd=new FormData();fd.append('foto',groot,'foto.jpg');fd.append('klein',klein,'klein.jpg');['titel','categorie','notitie','locatie'].forEach(k=>fd.append(k,f[k].value));st.textContent='Uploaden…';await ideeApi(fd);f.reset();f.foto.onchange();st.textContent='Opgeslagen ✓';laadIdeeen()}
catch(err){st.textContent=`Nog niet opgeslagen: ${err.message}. Je invoer staat er nog; probeer het opnieuw.`;if(err.status===401)ideeUit(err.message)}finally{btn.disabled=false}}}
document.getElementById('idee-beheer').onclick=async()=>{if(ideeBeheer){opslag.zet('nexusBeheercode','');ideeBeheer=false;return inspiration()}const c=prompt('Beheerderscode van de organisatie');if(!c)return;opslag.zet('nexusBeheercode',c.trim());try{ideeBeheer=(await ideeApi({actie:'controle'})).beheer}catch(e){ideeBeheer=false}if(!ideeBeheer){opslag.zet('nexusBeheercode','');alert('Onjuiste beheerderscode.')}inspiration()};
const dlg=document.getElementById('idee-dialog');dlg.addEventListener('click',e=>{if(e.target===dlg)dlg.close()});
if(ideeen)toonIdeeen();laadIdeeen()}
async function laadIdeeen(){try{const d=await ideeApi({actie:'lijst'});ideeen=d.ideeen;if(opslag.lees('nexusBeheercode')&&!ideeBeheer)ideeBeheer=(await ideeApi({actie:'controle'})).beheer;toonIdeeen()}
catch(err){if(err.status===401)return ideeUit(err.message);const g=document.getElementById('idee-galerij');if(g)g.innerHTML=`<p class="notice">De ideeën konden niet worden geladen: ${esc(err.message)}.</p>`}}
const fmt=n=>n.toLocaleString('nl-NL',{maximumFractionDigits:1});
function avatar(naam){const p=people.find(x=>fullName(x)===naam);return p&&p.afbeelding?`<img class="av" src="${p.afbeelding}-480.webp" alt="" loading="lazy">`:`<span class="av initials" aria-hidden="true">${p?initials(p):esc(naam.slice(0,1))}</span>`}
function scorebord(){const b=document.getElementById('idee-bord');if(!b)return;if(!ideeen.length){b.innerHTML='';return}
const tel=new Map();ideeen.forEach(i=>tel.set(i.door,(tel.get(i.door)||0)+1));const makers=[...tel].sort((x,y)=>y[1]-x[1]||x[0].localeCompare(y[0])).slice(0,3);
const top=ideeen.filter(i=>i.aantal>=2).sort((x,y)=>y.gemiddelde-x.gemiddelde||y.aantal-x.aantal).slice(0,3);
b.innerHTML=`<div class="board"><section class="card"><span class="eyebrow">MEESTE IDEEËN</span><ol>${makers.map(([n,c],k)=>`<li><span class="rank">${k+1}</span>${avatar(n)}<span class="bn">${esc(n)}</span><strong>${c}</strong></li>`).join('')}</ol></section><section class="card"><span class="eyebrow">BEST BEOORDEELD</span>${top.length?`<ol>${top.map((i,k)=>`<li><button class="board-idee" data-idee="${i.id}"><span class="rank">${k+1}</span><img class="av" src="${esc(i.klein)}" alt=""><span class="bn">${esc(i.titel)}<small>${esc(i.door)}</small></span><strong>★ ${fmt(i.gemiddelde)}</strong></button></li>`).join('')}</ol>`:'<p class="muted">Nog geen idee met twee of meer scores. Proef mee en geef sterren!</p>'}</section></div>`;
b.querySelectorAll('[data-idee]').forEach(x=>x.onclick=()=>openIdee(x.dataset.idee))}
function toonIdeeen(){const g=document.getElementById('idee-galerij'),fl=document.getElementById('idee-filter');if(!g)return;scorebord();const tel=c=>ideeen.filter(i=>c==='Alle'||i.categorie===c).length;
fl.innerHTML=['Alle',...categorieen].filter(c=>c==='Alle'||tel(c)).map(c=>`<button class="${ideeFilter===c?'selected':''}" aria-pressed="${ideeFilter===c}" data-cat="${c}">${c} <span>${tel(c)}</span></button>`).join('');
fl.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{ideeFilter=b.dataset.cat;toonIdeeen()});
const lijst=ideeen.filter(i=>ideeFilter==='Alle'||i.categorie===ideeFilter);
g.innerHTML=lijst.length?`<ul class="ideas">${lijst.map(i=>`<li><button class="person" data-idee="${i.id}"><img src="${esc(i.klein)}" loading="lazy" decoding="async" alt=""><span class="pname">${esc(i.titel)}</span><span class="soon">${esc(i.categorie)}${i.aantal?` · ★ ${fmt(i.gemiddelde)} (${i.aantal})`:''}</span><span class="door">${avatar(i.door)}${esc(i.door)}</span></button></li>`).join('')}</ul>`:'<p class="notice">Nog geen ideeën. Wie legt de eerste vondst vast?</p>';
g.querySelectorAll('[data-idee]').forEach(b=>b.onclick=()=>openIdee(b.dataset.idee))}
function scoreBlok(i){const s=document.getElementById('id-score'),eigen=i.door===opslag.lees('nexusNaam'),kan=opslag.lees('nexusSleutel')&&!eigen;
s.innerHTML=`<p class="score-now">${i.aantal?`<strong>★ ${fmt(i.gemiddelde)}</strong> <span class="muted">${i.aantal} ${i.aantal===1?'score':'scores'}</span>`:'<span class="muted">Nog geen scores</span>'}</p>${kan?`<p class="muted">${i.mijn?'Jouw score. Tik om aan te passen.':'Ook geproefd of gezien? Geef je score.'}</p><div class="stars" role="group" aria-label="Jouw score">${[1,2,3,4,5].map(n=>`<button data-ster="${n}" class="${i.mijn>=n?'on':''}" aria-pressed="${i.mijn===n}" aria-label="${n} ${n===1?'ster':'sterren'}">★</button>`).join('')}</div><p class="muted" id="id-score-st" role="status"></p>`:eigen?'<p class="muted">Je eigen idee; de anderen geven de score.</p>':''}`;
s.querySelectorAll('[data-ster]').forEach(b=>b.onclick=async()=>{const n=+b.dataset.ster,st=document.getElementById('id-score-st');st.textContent='Opslaan…';
try{await ideeApi({actie:'score',id:i.id,score:n});const som=(i.gemiddelde||0)*i.aantal-(i.mijn||0)+n;if(!i.mijn)i.aantal++;i.gemiddelde=Math.round(som/i.aantal*10)/10;i.mijn=n;scoreBlok(i);document.getElementById('id-score-st').textContent='Opgeslagen ✓';toonIdeeen()}
catch(err){st.textContent=`Niet opgeslagen: ${err.message}`}})}
function openIdee(id){const i=ideeen.find(x=>x.id===id),dlg=document.getElementById('idee-dialog'),img=document.getElementById('id-img'),del=document.getElementById('id-del');if(!i)return;img.src=i.foto;img.alt=i.titel;
document.getElementById('id-meta').textContent=[i.categorie,i.locatie,new Date(i.created_at).toLocaleString('nl-NL',{timeZone:'Europe/London',weekday:'short',hour:'2-digit',minute:'2-digit'})].filter(Boolean).join(' · ');
document.getElementById('id-title').textContent=i.titel;document.getElementById('id-door').innerHTML=`${avatar(i.door)}${esc(i.door)}`;document.getElementById('id-note').textContent=i.notitie||'';scoreBlok(i);del.hidden=!ideeBeheer;
del.onclick=async()=>{if(!confirm(`“${i.titel}” definitief verwijderen?`))return;try{await ideeApi({actie:'verwijder',id:i.id});dlg.close();ideeen=ideeen.filter(x=>x.id!==i.id);toonIdeeen()}catch(err){alert(err.message)}};if(!dlg.open)dlg.showModal()}
// Challenges: foto insturen, per challenge één stem (wisselen of intrekken), live stand. Zelfde toegang als het Inspiratieboek.
const chLijst=[['last-orders','01','Last Orders','De beste kroegfoto van het weekend.','Maak in de pub de foto die het weekend samenvat. Gezellig, gek of legendarisch.','assets/challenges/last-orders-voorbeeld'],['karaoke','02','Karaoke Hero','Wie pakt de microfoon?','Leg het beste karaokemoment vast. Durf jij zelf het podium op?','assets/challenges/karaoke-voorbeeld'],['ai-foto','03','Fake it in London','De meest fantastische AI-foto.','Maak met AI de wildste Londense foto van jezelf of de groep. Hoe ongeloofwaardiger, hoe beter.','assets/challenges/ai-foto-voorbeeld'],['bizar','04','Wat is dít nou?','Het meest bizarre product.','Spot in een winkel of op de markt het vreemdste product dat je tegenkomt. Maak een foto en vertel wat het is.'],['brits','05','Very British','Heel Engeland in één foto.','Rode bus, thee met melk, regen, een keurige rij: hoe meer clichés, hoe beter. Maak de meest over-de-top Britse foto van het weekend.'],['insta','06','Made for Instagram','De foto die online ontploft.','Licht, hoek, timing. Maak de foto waarvan iedereen denkt: die wil ik ook.'],['groep','07','Squad Goals','De beste groepsfoto.','Zoveel mogelijk van de groep op één foto, op de origineelste plek of in de gekste pose.'],['onbekende','08','Hello, Stranger','De beste foto met een onbekende.','Een Londenaar, een toerist of een bakker achter de toonbank: vraag of hij met je op de foto wil. Hoe verrassender, hoe beter.']];
let chData=null;
const kortNaam=n=>{const p=people.find(x=>fullName(x)===n);return p&&people.filter(x=>x.voornaam===p.voornaam).length===1?p.voornaam:n};
function challenges(){const sleutel=opslag.lees('nexusSleutel'),toegang=sleutel||opslag.lees('nexusGroepscode');
view.innerHTML=`<div class="section-head"><h2>Een beetje competitie.</h2><span class="muted">Hele weekend · live stand</span></div><p>Doe mee met een foto en stem per challenge op de leukste. Je stem kun je altijd wisselen.</p>${!toegang?'<p class="notice">Open je persoonlijke link uit de groepsapp om mee te doen en de foto’s te zien.</p>':sleutel?'':'<p class="notice">Je kijkt mee met de groepscode. Meedoen en stemmen kan met je persoonlijke link.</p>'}<div class="ch-lijst">${chLijst.map(c=>`<section class="card ch"><div class="ch-kop"><div><span class="number">${c[1]}</span><h3>${c[2]}</h3></div>${c[5]?`<img class="ch-vb" src="${c[5]}-klein.webp" alt="Voorbeeldfoto bij ${c[2]}" width="240" height="240">`:''}</div><p>${c[3]}</p><p class="muted">${c[4]}</p>${sleutel?`<details class="ch-add"><summary>+ Doe mee</summary><form class="idea-form" data-ch="${c[0]}"><label>Foto<input type="file" name="foto" accept="image/*" required></label><label>Wat zien we? <span class="muted">(optioneel)</span><input name="tekst" maxlength="300"></label><button class="utility">Insturen</button><p class="muted ch-status" role="status"></p></form></details>`:''}<div data-fotos="${c[0]}">${toegang?'<p class="muted">Laden…</p>':''}</div></section>`).join('')}</div><dialog id="ch-dialog" aria-labelledby="ch-titel"><form method="dialog"><button class="pd-close" aria-label="Sluiten">✕</button></form><img id="ch-img" alt=""><div class="id-body"><p class="id-door" id="ch-titel"></p><p id="ch-tekst"></p></div></dialog>`;
const dlg=document.getElementById('ch-dialog');dlg.addEventListener('click',e=>{if(e.target===dlg)dlg.close()});
view.querySelectorAll('form[data-ch]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const st=f.querySelector('.ch-status'),btn=f.querySelector('button'),file=f.foto.files[0];if(!file)return;btn.disabled=true;st.textContent='Foto verkleinen…';
try{const[groot,klein]=await Promise.all([verklein(file,1600,.82),verklein(file,480,.75)]);const fd=new FormData();fd.append('soort','challenge');fd.append('challenge',f.dataset.ch);fd.append('tekst',f.tekst.value);fd.append('foto',groot,'foto.jpg');fd.append('klein',klein,'klein.jpg');st.textContent='Uploaden…';await ideeApi(fd);f.reset();st.textContent='Ingestuurd ✓';f.closest('details').open=false;laadChallenges()}
catch(err){st.textContent=`Nog niet ingestuurd: ${err.message}. Probeer het opnieuw.`;if(err.status===401)chUit()}finally{btn.disabled=false}});
if(chData)toonChallenges();if(toegang)laadChallenges()}
function chUit(){['nexusSleutel','nexusNaam','nexusGroepscode'].forEach(k=>opslag.zet(k,''));chData=null;challenges()}
async function laadChallenges(){try{chData=await ideeApi({actie:'challenges'});if(opslag.lees('nexusBeheercode')&&!ideeBeheer)ideeBeheer=(await ideeApi({actie:'controle'})).beheer;toonChallenges()}
catch(err){if(err.status===401)return chUit();view.querySelectorAll('[data-fotos]').forEach(d=>d.innerHTML=`<p class="notice">De foto’s konden niet worden geladen: ${esc(err.message)}.</p>`)}}
function toonChallenges(){if(location.hash!=='#challenges')return;const ik=opslag.lees('nexusNaam'),sleutel=opslag.lees('nexusSleutel');
chLijst.forEach(([id])=>{const d=view.querySelector(`[data-fotos="${id}"]`);if(!d)return;const lijst=chData.inzendingen.filter(i=>i.challenge===id).sort((x,y)=>y.stemmen-x.stemmen||x.created_at.localeCompare(y.created_at));const max=lijst.length?lijst[0].stemmen:0;
d.innerHTML=lijst.length?`<ul class="ch-fotos">${lijst.map(i=>{const eigen=i.door===ik,mijn=chData.mijn[id]===i.id;return `<li class="ch-item${max&&i.stemmen===max?' lead':''}"><button class="ch-foto" data-open="${i.id}" aria-label="Foto van ${esc(i.door)} groot bekijken"><img src="${esc(i.klein)}" alt="" loading="lazy">${max&&i.stemmen===max?'<span class="ch-lead">Koploper</span>':''}</button><div class="ch-meta">${avatar(i.door)}<span class="ch-naam">${esc(kortNaam(i.door))}</span><button class="ch-stem${mijn?' on':''}" data-stem="${i.id}" aria-pressed="${mijn}" ${eigen||!sleutel?'disabled':''} aria-label="${eigen?'Je eigen foto':mijn?'Stem intrekken':'Stem op deze foto'}, ${i.stemmen} ${i.stemmen===1?'stem':'stemmen'}">♥︎ ${i.stemmen}</button></div>${eigen||ideeBeheer?`<button class="linkish ch-weg" data-weg="${i.id}">verwijderen</button>`:''}</li>`}).join('')}</ul>`:`<p class="muted">Nog geen inzendingen.${sleutel?' Wees de eerste!':''}</p>`});
view.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const i=chData.inzendingen.find(x=>x.id===b.dataset.open),img=document.getElementById('ch-img');img.src=i.foto;document.getElementById('ch-titel').innerHTML=`${avatar(i.door)}${esc(i.door)} · ♥︎ ${i.stemmen}`;document.getElementById('ch-tekst').textContent=i.tekst||'';document.getElementById('ch-dialog').showModal()});
view.querySelectorAll('[data-stem]').forEach(b=>b.onclick=async()=>{const i=chData.inzendingen.find(x=>x.id===b.dataset.stem),vorig=chData.mijn[i.challenge];
if(vorig===i.id){i.stemmen--;delete chData.mijn[i.challenge]}else{const v=chData.inzendingen.find(x=>x.id===vorig);if(v)v.stemmen--;i.stemmen++;chData.mijn[i.challenge]=i.id}toonChallenges();
try{await ideeApi({actie:'stem',id:i.id})}catch(err){alert(`Je stem is niet opgeslagen: ${err.message}`);laadChallenges()}});
view.querySelectorAll('[data-weg]').forEach(b=>b.onclick=async()=>{if(!confirm('Deze foto definitief verwijderen?'))return;try{await ideeApi({actie:'verwijder-inzending',id:b.dataset.weg});chData.inzendingen=chData.inzendingen.filter(x=>x.id!==b.dataset.weg);toonChallenges()}catch(err){alert(err.message)}})}
// Wachtkamer: tot het verzamelen op Schiphol (vr 2 okt 07:00 NL-tijd) alleen header, countdown en beginscherm-uitleg.
// Organisatie: ?open zet de site op dit toestel open, ?dicht zet de wachtkamer terug.
const OPEN_OM=Date.UTC(2026,9,2,5,0,0);
{const q=new URLSearchParams(location.search);if(q.has('open'))opslag.zet('nexusOpen','1');if(q.has('dicht'))opslag.zet('nexusOpen','')}
const gesloten=()=>Date.now()<OPEN_OM&&!opslag.lees('nexusOpen');
let aftelTimer=null;
function wachtkamer(){document.body.classList.add('gesloten');const naam=opslag.lees('nexusNaam'),sleutel=opslag.lees('nexusSleutel'),ios=/iPhone|iPad|iPod/.test(navigator.userAgent),opScherm=navigator.standalone||matchMedia('(display-mode: standalone)').matches;
const iphone=`<article class="card stap"><h3>iPhone</h3><ol><li>Open deze link in <strong>Safari</strong>. Zit je in WhatsApp? Tik dan op <strong>Openen in Safari</strong> (het kompasje).</li><li>Tik op <strong>Deel</strong>: het vierkantje met het pijltje omhoog.</li><li>Kies <strong>Zet op beginscherm</strong> en tik op <strong>Voeg toe</strong>.</li></ol></article>`,
android=`<article class="card stap"><h3>Android</h3><ol><li>Open deze link in <strong>Chrome</strong>.</li><li>Tik rechtsboven op <strong>⋮</strong> (drie puntjes).</li><li>Kies <strong>Toevoegen aan startscherm</strong> of <strong>App installeren</strong>.</li></ol></article>`;
view.innerHTML=`<section class="aftel"><p class="eyebrow">VERZAMELEN OP SCHIPHOL PLAZA · VRIJDAG 2 OKTOBER · 07:00</p><div class="aftel-klok" role="timer" aria-live="off">${['dagen','uur','min','sec'].map(e=>`<div><strong data-teller="${e}">00</strong><span>${e}</span></div>`).join('')}</div>
${sleutel?`<p class="aftel-hoi" id="aftel-hoi">${naam?`Hoi ${esc(naam.split(' ')[0])}! Dit is jouw persoonlijke link. Deel hem niet door, dan weet de site altijd dat jij het bent.`:'Even kijken wie je bent…'}</p>`:''}
<p class="aftel-tekst">Vrijdag gaat hier je reisgids open: het programma, de groep, de plekken, ideeën en challenges. Zet hem nu alvast op je beginscherm, dan heb je hem in Londen met één tik bij de hand. Ook zonder internet.</p></section>
<div class="section-head"><h2>Zet hem op je beginscherm.</h2>${opScherm?'<span class="muted">Staat er al op ✓</span>':''}</div><div class="cards">${ios?iphone+android:android+iphone}</div>`;
const zet=()=>{let r=Math.max(0,OPEN_OM-Date.now());if(r===0){clearInterval(aftelTimer);aftelTimer=null;document.body.classList.remove('gesloten');return render()}
const d=Math.floor(r/864e5),u=Math.floor(r/36e5)%24,m=Math.floor(r/6e4)%60,sec=Math.floor(r/1e3)%60;
[['dagen',d],['uur',u],['min',m],['sec',sec]].forEach(([k,v])=>{const el=view.querySelector(`[data-teller="${k}"]`);if(el)el.textContent=String(v).padStart(2,'0')})};
zet();clearInterval(aftelTimer);aftelTimer=setInterval(zet,1000);
if(sleutel&&!naam)ideeApi({actie:'controle'}).then(d=>{if(d.naam){opslag.zet('nexusNaam',d.naam);const h=document.getElementById('aftel-hoi');if(h)h.textContent=`Hoi ${d.naam.split(' ')[0]}! Dit is jouw persoonlijke link. Deel hem niet door, dan weet de site altijd dat jij het bent.`}}).catch(()=>{const h=document.getElementById('aftel-hoi');if(h)h.remove()})}
function render(){if(placesMap){placesMap.remove();placesMap=null;}if(gesloten())return wachtkamer();const route=/^#ik=/.test(location.hash)?'inspiratie':location.hash.slice(1)||'programma';document.querySelectorAll('nav a').forEach(a=>{const active=a.hash==='#'+route;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});({programma:program,groep:group,challenges,plekken:places,inspiratie:inspiration,praktisch:practical}[route]||program)()}
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
window.addEventListener('hashchange',()=>{render();view.scrollIntoView({behavior:'smooth',block:'start'})});render();
